SistemaDeNotas/Controllers/AvisosController.cs
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using SistemaDeNotas.Enums;
using SistemaDeNotas.Filters;
using SistemaDeNotas.Helper;
using SistemaDeNotas.Models;
using SistemaDeNotas.Repositorio;

namespace SistemaDeNotas.Controllers
{
    [PaginaRestritaSomenteAdmin]
    [EnableCors]
    public class AvisosController : Controller
    {
        private readonly ISessao _sessao;
        private readonly IAvisosRepositorio _avisosRepositorio;

        public AvisosController(IAvisosRepositorio avisosRepositorio,
                                ISessao sessao)
        {
            _sessao = sessao;
            _avisosRepositorio = avisosRepositorio;
        }
        public IActionResult Index()
        {
            List<AvisosModel> avisos = _avisosRepositorio.BuscarTodosAdm();
            return View(avisos);
        }
        public IActionResult Criar()
        {

            return View();
        }
        public IActionResult Editar(int id)
        {
            AvisosModel aviso = _avisosRepositorio.ListarPorId(id);
            return View(aviso);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            AvisosModel aviso = _avisosRepositorio.ListarPorId(id);
            return View(aviso);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                UsuarioModel usuario = new UsuarioModel();
                usuario.Perfil = usuarioLogado.Perfil;
                if (usuario.Perfil != PerfilEnum.Admin) throw new Exception(" Usuário não é admin");
                bool apagado = _avisosRepositorio.Apagar(id);
                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Apagado com sucesso";
                }
                else
                {
                    TempData["MensagemErro"] = "Falha ao apagar";
                }
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Falha ao apagar, tente novamente, detalhes:{erro.Message} ";
                return RedirectToAction("Index");
            }
        }
        public IActionResult ListarAvisos()
        {
            List<AvisosModel> avisos = _avisosRepositorio.BuscarTodosAdm();
            return PartialView("_Avisos", avisos);
        }

        [HttpPost]
        public IActionResult Criar(AvisosModel aviso)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    AvisosModel aviso2 = null;
                    aviso2 = new AvisosModel()
                    {
                        AvisoCorpo = aviso.AvisoCorpo,
                        AvisoTitulo = aviso.AvisoTitulo

                    };


                    UsuarioModel UsuarioN = new UsuarioModel();
                    UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                    UsuarioN.Perfil = usuarioLogado.Perfil;
                    if (UsuarioN.Perfil != PerfilEnum.Admin) throw new Exception(" Usuário não é admin");
                    aviso2 = _avisosRepositorio.Adicionar(aviso2);
                    TempData["MensagemSucesso"] = "Inserido com sucesso";
                    return RedirectToAction("Index");
                }
                return View(aviso);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Falha ao inserir, tente novamente, detalhes:{erro.Message} ";
                return RedirectToAction("Index");
            }

        }

        [HttpPost]
        public IActionResult Alterar(AvisosModel aviso)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                    UsuarioModel usuario = new UsuarioModel();
                    usuario.Perfil = usuarioLogado.Perfil;
                    if (usuario.Perfil != PerfilEnum.Admin) throw new Exception(" Usuário não é admin");
                    aviso = _avisosRepositorio.Atualizar(aviso);
                    TempData["MensagemSucesso"] = "Alterado com sucesso";
                    return RedirectToAction("Index");
                }

                return View("Editar", aviso);
            }

            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Falha ao Alterar, tente novamente, detalhes:{erro.Message} ";
                return RedirectToAction("Index");
            }
        }
    }
}

SistemaDeNotas/Views/Avisos/ApagarConfirmacao.cshtml
@model AvisosModel
@{
    ViewData["Title"] = "Confirmação Apagar Avisos";
}


<div class="text-center">
    <h3> Deseja realmente apagar o avio (@Model.AvisoTitulo)</h3>
</div>
<a class="btn btn-success" asp-controller="Avisos" asp-action="Index" role="button">Cancelar</a>
<a class="btn btn-danger" asp-controller="Avisos" asp-action="Apagar" role="button" asp-route-id="@Model.Id">Confirmar</a>

SistemaDeNotas/Views/Avisos/Criar.cshtml
@model AvisosModel
@{
    ViewData["Title"] = "Cadastrar Avisos";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar Avisos</h1>

</div>

@if(TempData["MensagemSucesso"]!= null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
}
@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemErro"]
    </div>
}

<form asp-controller="Avisos" asp-action="Criar" method="post">
    <div class="form-group">
        <label for="avisotitulo">Titulo do Aviso</label>
        <input type="text" asp-for="AvisoTitulo" class="form-control" placeholder="Digite aqui a titulo...">
        @Html.ValidationMessageFor(x=>x.AvisoTitulo)
    </div>
    <br />
    <div class="form-group">
        <label for="avisocorpo">Digite Aqui o Aviso</label>
        <textarea name="AvisoCorpo" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
        <br />
    </div>
    <button type="submit" class="btn btn-primary">Inserir</button>
    <a class="btn btn-secondary btn-block" asp-controller="Avisos" asp-action="Index"> Voltar</a>
</form>

SistemaDeNotas/Views/Avisos/Editar.cshtml
@model AvisosModel
@{
    ViewData["Title"] = "Editar Aviso";
}

<div class="text-center">

    <h1 class="display-4">Alterar aviso</h1>

</div>

<form asp-controller="Avisos" asp-action="Alterar" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label for="avisotitulo">Título do Aviso</label>
        <input type="text" asp-for="AvisoTitulo" class="form-control" placeholder="Digite aqui o titulo">
        @Html.ValidationMessageFor(x=>x.AvisoTitulo)
    </div>
    <br />
    <div class="form-group">
        <label for="avisocorpo">Aviso</label>
        <input type="text" asp-for="AvisoCorpo" class="form-control" placeholder="Digite aqui o Aviso">
        @Html.ValidationMessageFor(x=>x.AvisoCorpo)
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Alterar</button>
    <a class="btn btn-secondary btn-block" asp-controller="Avisos" asp-action="Index"> Voltar</a>
</form>

SistemaDeNotas/Views/Avisos/Index.cshtml
@model List<AvisosModel>
@{
    ViewData["Title"] = "Administrar Avisos";
}

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemErro"]
    </div>
}
@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
}

<div class="text-center">

    <div class="">
        <a class="btn btn-success d-grid gap-2" role="button" asp-controller="Avisos" asp-action="Criar"> Adicionar Aviso</a>

    </div>
    <h1 class="display-4">Esses são os avisos Cadastrados</h1>

    <table class="display" id="table-usuarios" style="width:100%">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Titulo:</th>
                <th scope="col">Aviso:</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var aviso in Model)
                {
                    <tr>
                        <th scope="row">@aviso.Id</th>
                        <td>@aviso.AvisoTitulo</td>
                        <td>@aviso.AvisoCorpo</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@aviso.Id" asp-controller="Avisos" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@aviso.Id" asp-controller="Avisos" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <th scope="row"></th>
                    <td></td>
                    <td>Nehum aviso encontrado!</td>
                    <td></td>
                </tr>
            }
        </tbody>
    </table>
</div>