SistemaDeNotas/Controllers/AdminNotasController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaDeNotas.Enums;
using SistemaDeNotas.Filters;
using SistemaDeNotas.Helper;
using SistemaDeNotas.Models;
using SistemaDeNotas.Repositorio;
using System;

namespace SistemaDeNotas.Controllers
{
    
    public class AdminNotasController : Controller
    {
            private readonly INotaRepositorio _notaRepositorio;
            private readonly ISessao _sessao;
            private readonly IUsuarioRepositorio _usuarioRepositorio;
            private readonly IEmail _email;
        public AdminNotasController(INotaRepositorio notaRepositorio,
                                   ISessao sessao,
                                   IUsuarioRepositorio usuarioRepositorio,
                                   IEmail email)
            {
                _notaRepositorio = notaRepositorio;
                _sessao = sessao;
                 _usuarioRepositorio = usuarioRepositorio;
                _email = email;
             }
             [PaginaRestritaSomenteAdmin]
            public IActionResult Index()
            {

            List<NotaModel> notas = _notaRepositorio.BuscarTodosAdm();
            return View(notas);

             }
             [PaginaRestritaSomenteAdmin]
            public IActionResult Criar()
            {

            return View();
            }
             [PaginaRestritaSomenteAdmin]
             public IActionResult Editar(int id)
            {
                NotaModel nota = _notaRepositorio.ListarPorId(id);
                return View(nota);
            }
                [PaginaRestritaSomenteAdmin]
              public IActionResult ApagarConfirmacao(int id)
            {
                NotaModel nota = _notaRepositorio.ListarPorId(id);
                return View(nota);
            }
                [PaginaRestritaSomenteAdmin]
             public IActionResult Apagar(int id)
            {
                try
                {
                    UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                    UsuarioModel usuario = new UsuarioModel();
                    usuario.Perfil = usuarioLogado.Perfil;
                    if (usuario.Perfil != PerfilEnum.Admin) throw new Exception(" Usuário não é admin");
                    bool apagado = _notaRepositorio.Apagar(id);
                    if (apagado)
                    {
                        TempData["MensagemSucesso"] = "Apagado com sucesso";
                    }
                    else
                    {
                        TempData["MensagemErro"] = "Falha ao apagar";
                    }
                    return RedirectToAction("Index");
                }
                catch (Exception erro)
                {
                    TempData["MensagemErro"] = $"Falha ao apagar, tente novamente, detalhes:{erro.Message} ";
                    return RedirectToAction("Index");
                }
            }
            [HttpPost]
             [PaginaRestritaSomenteAdmin]
             public IActionResult Criar(NotaModel nota)
            {
                try
                {
                    if (ModelState.IsValid)
                    {

                    NotaModel nota2 = null;
                    nota2 = new NotaModel()
                    {
                        UsuarioID = nota.UsuarioID,
                        Materia = nota.Materia,
                        Nota1Bimestre = nota.Nota1Bimestre,
                        Nota2Bimestre = nota.Nota2Bimestre,
                        Nota3Bimestre = nota.Nota3Bimestre,
                        Nota4bimestre = nota.Nota4bimestre,
                        UsuarioNome= nota.UsuarioNome,
                        UsuarioTurma = nota.UsuarioTurma,
                        UsuarioEmail = nota.UsuarioEmail

                    };


                    UsuarioModel UsuarioN = new UsuarioModel();
                    UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                    UsuarioModel nome = _usuarioRepositorio.BuscarNome(nota2.UsuarioID);
                    nota2.UsuarioNome = nome.Nome;
                    nota2.UsuarioTurma= nome.Turma;
                    nota2.UsuarioEmail= nome.Email;
                    string emailenviar = nota2.UsuarioEmail;
                    UsuarioN.Perfil = usuarioLogado.Perfil;

                    if (usuarioLogado != null)
                    {
                        string mensagem = $"Nova nota adicionada para seu Usuario, acesse o sistema e confira! https://sistemadenotas.azurewebsites.net/ ";
                        bool emailEnviado = _email.Enviar(emailenviar, "Nova Nota Cadastrada - E. E. Santa Terezinha", mensagem);

                    }
                    if (UsuarioN.Perfil != PerfilEnum.Admin) throw new Exception(" Usuário não é admin");
                    nota2 = _notaRepositorio.Adicionar(nota2);
                        TempData["MensagemSucesso"] = "Inserido com sucesso";
                        return RedirectToAction("Index", "Usuario");
                    }
                    return View(nota);
                }
                catch (Exception erro)
                {
                    TempData["MensagemErro"] = $"Falha ao inserir, tente novamente, detalhes:{erro.Message} ";
                    return RedirectToAction("Index");
                }

            }
            [HttpPost]
                [PaginaRestritaSomenteAdmin]
             public IActionResult Alterar(NotaModel nota)
            {

                try
                {
                    if (ModelState.IsValid)
                    {

                   
                    UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                    UsuarioModel usuario = new UsuarioModel();
                    UsuarioModel nome = _usuarioRepositorio.BuscarNome(nota.UsuarioID);

                    string mensagem = $"Nova nota adicionada para seu Usuario, acesse o sistema e confira! https://sistemadenotas.azurewebsites.net/ ";
                    bool emailEnviado = _email.Enviar(nota.UsuarioEmail, "Nova Nota Cadastrada - E. E. Santa Terezinha", mensagem);



                    usuario.Perfil = usuarioLogado.Perfil;


                    if (usuario.Perfil != PerfilEnum.Admin) throw new Exception(" Usuário não é admin");

           
                    nota = _notaRepositorio.Atualizar(nota);
                        TempData["MensagemSucesso"] = "Alterado com sucesso";
                        return RedirectToAction("Index");
                    }

                return View("Editar", nota);
                }

                catch (Exception erro)
                {
                    TempData["MensagemErro"] = $"Falha ao Alterar, tente novamente, detalhes:{erro.Message} ";
                    return RedirectToAction("Index");
                }
            }
    }
}

SistemaDeNotas/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaDeNotas.Filters;
using SistemaDeNotas.Models;
using SistemaDeNotas.Repositorio;

namespace SistemaDeNotas.Controllers
{
    [PaginaRestritaSomenteAdmin]
    public class UsuarioController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly INotaRepositorio _notaRepositorio;
        public UsuarioController(IUsuarioRepositorio usuarioRepositorio,
                                 INotaRepositorio notaRepositorio)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _notaRepositorio = notaRepositorio;
        }
        public IActionResult Index()
        {
            List<UsuarioModel> usuarios = _usuarioRepositorio.BuscarTodos();

            return View(usuarios);
        }
        public IActionResult Criar()
        {
            return View();
        }
        public IActionResult Editar(int id)
        {
            UsuarioModel usuario = _usuarioRepositorio.ListarPorId(id);
            return View(usuario);
        }
        public IActionResult ApagarConfirmacao(int id)
        {
            UsuarioModel usuario = _usuarioRepositorio.ListarPorId(id);
            return View(usuario);
        }
        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _usuarioRepositorio.Apagar(id);
                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Apagado com sucesso";
                }
                else
                {
                    TempData["MensagemErro"] = "Falha ao apagar";
                }
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Falha ao apagar, tente novamente, detalhes:{erro.Message} ";
                return RedirectToAction("Index");
            }
        }

        public IActionResult ListarNotasPorUsuarioId(int id)
        {
            List<NotaModel> notas = _notaRepositorio.BuscarTodos(id);
            return PartialView("_NotasUsuario", notas);
        }


        [HttpPost]
        public IActionResult Criar(UsuarioModel usuarios)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    usuarios = _usuarioRepositorio.Adicionar(usuarios);
                    TempData["MensagemSucesso"] = "Inserido com sucesso";
                    return RedirectToAction("Index");
                }
                return View(usuarios);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Falha ao inserir, tente novamente, detalhes:{erro.Message} ";
                return RedirectToAction("Index");
            }

        }
        [HttpPost]
        public IActionResult Editar(UsuarioSemSenhaModel usuarioSemSenhaModel)
        {

            try
            {
                UsuarioModel usuario = null;
                if (ModelState.IsValid)
                {
                    usuario = new UsuarioModel()
                    {
                        Id = usuarioSemSenhaModel.Id,
                        Nome = usuarioSemSenhaModel.Nome,
                        Email = usuarioSemSenhaModel.Email,
                        Turma = usuarioSemSenhaModel.Turma,
                        Perfil = usuarioSemSenhaModel.Perfil
                        
                    };
                   usuario = _usuarioRepositorio.Atualizar(usuario);
                    TempData["MensagemSucesso"] = "Alterado com sucesso";
                    return RedirectToAction("Index");
                }

                return View("Editar", usuario);
            }

            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Falha ao Alterar, tente novamente, detalhes:{erro.Message} ";
                return RedirectToAction("Index");
            }
        }
    }
}

SistemaDeNotas/Views/Usuario/ApagarConfirmacao.cshtml
@model UsuarioModel
@{
    ViewData["Title"] = "Confirmação Apagar Usuario";
}

<div class="text-center">
    <h3> Deseja realmente apagar o usuario (@Model.Usuario)</h3>
</div>
<a class="btn btn-success" asp-controller="Usuario" asp-action="Index" role="button">Cancelar</a>
<a class="btn btn-danger" asp-controller="Usuario" asp-action="Apagar" role="button" asp-route-id="@Model.Id">Confirmar</a>

SistemaDeNotas/Views/Usuario/Criar.cshtml
@using SistemaDeNotas.Enums;
@model UsuarioModel
@{
    ViewData["Title"] = "Cadastrar Usuario";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar Usuarios</h1>

</div>

@if(TempData["MensagemSucesso"]!= null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
}
@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemErro"]
    </div>
}

<form asp-controller="Usuario" asp-action="Criar" method="post">
    <div class="form-group">
        <label for="usuario">Usuário</label>
        <input type="text" asp-for="Usuario" class="form-control" placeholder="Digite aqui o usuario">
        @Html.ValidationMessageFor(x=>x.Usuario)
    </div>
    <br />
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite aqui o Nome">
        @Html.ValidationMessageFor(x=>x.Nome)
    </div>
    <br />
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" asp-for="Email" class="form-control" placeholder="Digite aqui o Email">
    </div>
    <br />
    <div class="form-group">
        <label for="turma">Turma</label>
        <input type="text" asp-for="Turma" class="form-control" placeholder="Digite aqui a Turma">
        @Html.ValidationMessageFor(x=>x.Turma)
    </div>
    <br />
    <div class="form-group">
        <label for="senha">Senha</label>
        <input type="password" asp-for="Senha" class="form-control" placeholder="Digite aqui a Senha">
        @Html.ValidationMessageFor(x=>x.Senha)
    </div> 
    <br />
    <div class="form-group">
        <label for="perfil" class="form-label">Perfil</label>
        <select asp-for="Perfil" class="form-control">
            <option value="0">Selecione</option>
            <option value="@PerfilEnum.Admin">Admin</option>
            <option value="@PerfilEnum.Padrao">Padrão</option>
        </select>
        @Html.ValidationMessageFor(x=>x.Perfil)
    </div>

    <br />
    <button type="submit" class="btn btn-primary">Inserir</button>
</form>

SistemaDeNotas/Views/Usuario/Editar.cshtml
@using SistemaDeNotas.Enums;
@model UsuarioModel
@{
    ViewData["Title"] = "Editar Usuario";
}

<div class="text-center">

    <h1 class="display-4">Editar Usuarios</h1>

</div>

@if(TempData["MensagemSucesso"]!= null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
}
@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemErro"]
    </div>
}

<form asp-controller="Usuario" asp-action="Editar" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite aqui o Nome">
        @Html.ValidationMessageFor(x=>x.Nome)
    </div>
    <br />
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" asp-for="Email" class="form-control" placeholder="Digite aqui o Email">
    </div>
    <br />
    <div class="form-group">
        <label for="turma">Turma</label>
        <input type="text" asp-for="Turma" class="form-control" placeholder="Digite aqui a Turma">
        @Html.ValidationMessageFor(x=>x.Turma)
    </div>
    <br />
    <div class="form-group">
        <label for="perfil" class="form-label">Perfil</label>
        <select asp-for="Perfil" class="form-control">
            <option value="0">Selecione</option>
            <option value="@PerfilEnum.Admin">Admin</option>
            <option value="@PerfilEnum.Padrao">Padrão</option>
        </select>
        @Html.ValidationMessageFor(x=>x.Perfil)
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Editar</button>
</form>

SistemaDeNotas/Views/Usuario/_NotasUsuario.cshtml
@model List<NotaModel>

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema De Notas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaDeNotas.styles.css" asp-append-version="true" />


</head>
<body>
    <table class="display" id="table-notas-usuario">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Matéria</th>
            <th scope="col">Nota 1° Bimestre</th>
            <th scope="col">Nota 2° Bimestre</th>
            <th scope="col">Nota 3° Bimestre</th>
            <th scope="col">Nota 4° Bimestre</th>
            <th scope="col">Média Anual</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if(Model != null && Model.Any())
        {
            @foreach (var nota in Model)
            {
                    if (nota.Nota1Bimestre == null)
                    {
                        nota.Nota1Bimestre = 0;
                    }
                    if (nota.Nota2Bimestre == null)
                    {
                        nota.Nota2Bimestre = 0;
                    }
                    if (nota.Nota3Bimestre == null)
                    {
                        nota.Nota3Bimestre = 0;
                    }
                    if (nota.Nota4bimestre == null)
                    {
                        nota.Nota4bimestre = 0;
                    }
                <tr>
                    <th scope="row">@nota.Id</th>
                    <td>@nota.Materia</td>
                    <td>@nota.Nota1Bimestre</td>
                    <td>@nota.Nota2Bimestre</td>
                    <td>@nota.Nota3Bimestre</td>
                    <td>@nota.Nota4bimestre</td>
                    <td>
                            @{
                                var total = nota.Nota1Bimestre + nota.Nota2Bimestre + nota.Nota3Bimestre + nota.Nota4bimestre;
                            }
                            @total
                    </td>
                    <td>
                        <div class="btn-group" role="group">
                            <a role="button" class="btn btn-primary" asp-route-id="@nota.Id" asp-controller="AdminNotas" asp-action="Editar">Editar</a>
                            <a role="button" class="btn btn-danger" asp-route-id="@nota.Id" asp-controller="AdminNotas" asp-action="ApagarConfirmacao">Apagar</a>
                        </div>
                    </td>

                </tr>
            }
        }
        else
        {
            <tr>
                <th scope="row"></th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        }
    </tbody>
</table>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

SistemaDeNotas/Views/Usuario/index.cshtml
@model List<UsuarioModel>
@{
    ViewData["Title"] = "Listagem de Usuarios";
}

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemErro"]
    </div>
}
@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
}
<div class="text-center">

    <div class="">
        <a class="btn btn-success d-grid gap-2" role="button" asp-controller="Usuario" asp-action="Criar"> Adicionar Usuario</a>

    </div>
    <h1 class="display-4">Usuarios Cadastrados</h1>
    <table class="display" id="table-usuarios" style="width:100%">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Usuario:</th>
                <th scope="col">Nome:</th>
                <th scope="col">Turma:</th>
                <th scope="col">Email:</th>
                <th scope="col">Notas:</th>
                <th scope="col">Perfil:</th>
                <th scope="col">Data de Alteração:</th>
               <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach(var usuario in Model){
                    <tr>
                        <th scope="row">@usuario.Id</th>
                        <td>@usuario.Usuario</td>
                        <td>@usuario.Nome</td>
                        <td>@usuario.Turma</td>
                        <td>@usuario.Email</td>
                        <td>
                            <a href="javascript:" usuario-id="@usuario.Id" class="btn btn-success btn-sm btn-total-notas" data-bs-toggle="modal" data-bs-target="#modalNotasUsuario" id="teste2">
                                @(usuario.Notas != null && usuario.Notas.Any() ? usuario.Notas.Count() : 0)
                            </a>
                            
                        </td>
                        <td>@(usuario.Perfil == SistemaDeNotas.Enums.PerfilEnum.Admin ? "Adm" : "Padrão")</td>
                        <td>@usuario.DataAtualizacao </td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@usuario.Id" asp-controller="Usuario" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@usuario.Id" asp-controller="Usuario" asp-action="ApagarConfirmacao">Apagar</a>
                                <a role="button" class="btn btn-success" asp-route-id="@usuario.Id" asp-controller="AdminNotas" asp-action="Criar">Criar</a>
                            </div>
                           
 
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <th scope="row"></th>
                    <th scope="row"></th>
                    <th scope="row"></th>
                    <th scope="row"></th> 
                    <th scope="row"></th>
                    <th scope="row"></th>
                    <th scope="row"></th>
               </tr>
            }
        </tbody>
    </table>


    <!-- Modal -->
    <div class="modal fade" id="modalNotasUsuario" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Notas</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div id="listaNotasUsuario"></div>
                </div>
            </div>
        </div>
    </div>
</div>