SistemaDeNotas/Controllers/AlterarSenhaController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaDeNotas.Helper;
using SistemaDeNotas.Models;
using SistemaDeNotas.Repositorio;

namespace SistemaDeNotas.Controllers
{
    public class AlterarSenhaController : Controller
    {
        private readonly IUsuarioRepositorio _usarioRepositorio;
        private readonly ISessao _sessao;

        public AlterarSenhaController(IUsuarioRepositorio usuarioRepositorio,
                                       ISessao sessao)
        {
            _usarioRepositorio = usuarioRepositorio;    
            _sessao = sessao;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Alterar(AlterarSenhaModel alterarSenhaModel)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                    alterarSenhaModel.Id = usuarioLogado.Id;
                    _usarioRepositorio.AlterarSenha(alterarSenhaModel);
                    TempData["MensagemSucesso"] = "Senha alterada com sucesso";
                    return View("Index", alterarSenhaModel);
                }

                return View("Index", alterarSenhaModel);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Falha ao alterar a senha, tente novamente, detalhes: {erro.Message} ";
                return View("Index", alterarSenhaModel);
            }
        }
    }
}

SistemaDeNotas/Controllers/NotaController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaDeNotas.Enums;
using SistemaDeNotas.Filters;
using SistemaDeNotas.Helper;
using SistemaDeNotas.Models;
using SistemaDeNotas.Repositorio;

namespace SistemaDeNotas.Controllers
{
    [PaginaParaUsuarioLogado]
    public class NotaController : Controller
    {
        private readonly INotaRepositorio _notaRepositorio;
        private readonly ISessao _sessao;
        public NotaController(INotaRepositorio notaRepositorio,
                               ISessao sessao)
        {
            _notaRepositorio = notaRepositorio;
            _sessao = sessao;

        }
        public IActionResult Index()
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
            List<NotaModel> notas = _notaRepositorio.BuscarTodos(usuarioLogado.Id);
            return View(notas);
        }
        public IActionResult Criar()
        {
            return View();
        }
        public IActionResult Editar(int id)
        {
            NotaModel nota =  _notaRepositorio.ListarPorId(id);
            return View(nota);
        }
        public IActionResult ApagarConfirmacao(int id)
        {
            NotaModel nota = _notaRepositorio.ListarPorId(id);
            return View(nota);
        }
        public IActionResult Apagar(int id)
        {
            try
            {
                UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                UsuarioModel usuario = new UsuarioModel();
                usuario.Perfil = usuarioLogado.Perfil;
                if (usuario.Perfil != PerfilEnum.Admin) throw new Exception(" Usuário não é admin");
                bool apagado = _notaRepositorio.Apagar(id);
                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Apagado com sucesso";
                }
                else
                {
                    TempData["MensagemErro"] = "Falha ao apagar";
                }
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Falha ao apagar, tente novamente, detalhes:{erro.Message} ";
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public IActionResult Criar(NotaModel nota)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                    UsuarioModel usuario = new UsuarioModel();
                    usuario.Perfil = usuarioLogado.Perfil;
                    if(usuario.Perfil != PerfilEnum.Admin) throw new Exception(" Usuário não é admin");
                    //nota.UsuarioID = usuarioLogado.Id;
                    
                    nota = _notaRepositorio.Adicionar(nota);
                    TempData["MensagemSucesso"] = "Inserido com sucesso";
                     return RedirectToAction("Index");
                }
                return View(nota);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Falha ao inserir, tente novamente, detalhes:{erro.Message} ";
                return RedirectToAction("Index");
            }
            
        }
        [HttpPost]
        public IActionResult Alterar(NotaModel nota)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                    UsuarioModel usuario = new UsuarioModel();
                    usuario.Perfil = usuarioLogado.Perfil;
                    if (usuario.Perfil != PerfilEnum.Admin) throw new Exception(" Usuário não é admin");
                    //nota.UsuarioID = usuarioLogado.Id;
                    nota = _notaRepositorio.Atualizar(nota);
                    TempData["MensagemSucesso"] = "Alterado com sucesso";
                    return RedirectToAction("Index");
                }

                return View("Editar", nota);
            }

            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Falha ao Alterar, tente novamente, detalhes:{erro.Message} ";
                return RedirectToAction("Index");
            }
        }
    }
}

SistemaDeNotas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema De Notas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaDeNotas.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.4.1/css/responsive.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

</head>

<body>

    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @await Component.InvokeAsync("Menu")
            </div>
        </nav>

        
        <div class="menu-mobile" id="menu-mobile">

        <div class="btn-fechar"><i class="bi bi-x-lg"></i></div>
            <nav>
                <ul>
                    <li class="item-menu">
                        <span class="icon"><i class="bi bi-house-fill"></i></span>
                        <a class="btn" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                    </li>
                  
                    <li class="item-menu">
                        <span class="icon"><i class="bi bi-journal-check"></i></span>
                            <a class="btn" asp-area="" asp-controller="Nota" asp-action="Index">Notas</a>
                    </li>

                    <li class="item-menu">
                        <span class="icon"><i class="bi bi-file-lock2-fill"></i></span>
                        <a class="btn" asp-area="" asp-controller="AlterarSenha" asp-action="Index">Alterar Senha</a>
                    </li>
                    <li class="item-menu">
                        <span class="icon"><i class="bi bi-toggle-on"></i></span>
                        <a id="toggle" class="btn">Alterar Tema</a>
                    </li>
                    <li class="item-menu">
                        <span class="icon"><i class="bi bi-box-arrow-left"></i></span>
                        <a class="btn" asp-area="" asp-controller="Login" asp-action="Sair">Sair</a>
                    </li>
                    
                </ul>
            </nav>

        </div>
        <div class="overlay-menu" id="overlay-menu"></div>
    </header>

   
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="smoothscroll-top">
        <span class="scroll-top-inner">
            <i class="fa fa-2x fa-arrow-circle-up"></i>
        </span>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.4.1/js/dataTables.responsive.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/ce66a97387.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SistemaDeNotas/Views/Shared/_LayoutDeslogado.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema De Notas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaDeNotas.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.4.1/css/responsive.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sistema De Notas</a>
                <div class="buttons">
                    <!-- botão para fazer a troca de estados dark/light -->
                    <button id="toggle" class="btn btn-dark">Alterar Tema</button>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="display: block; position: relative; width: 100%; clear: both;">
        <div class="container">
            &copy; 2023 - SistemaDeNotas - by Bruno Vinicius
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.4.1/js/dataTables.responsive.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>